---
# This is a Terraform-managed file; manual changes will be overwritten.
# https://github.com/vpc-dev/github-organization/blob/main/templates/.markdown-lint.yml

default: true

MD013:
  line_length: false

...
