---
# This is a Terraform-managed file; manual changes will be overwritten.
# https://github.com/vpc-dev/github-organization/blob/main/templates/workflows/markdown.yml

name: "Documentation: Link Checker"

# yamllint disable-line rule:truthy
on:
  pull_request:

jobs:
  markdown:
    name: Markdown
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - name: '☁️ Checkout Repository'
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      # https://github.com/gaurav-nelson/github-action-markdown-link-check
      - name: Check Links in Markdown files
        uses: gaurav-nelson/github-action-markdown-link-check@1.0.14
        with:
          check-modified-files-only: "no"
          config-file: ".markdown-link-check.json"
          file-extension: ".md"
          use-verbose-mode: "yes"

...
