---
# This is a Terraform-managed file; manual changes will be overwritten.
# https://github.com/vpc-dev/github-organization/blob/main/templates/workflows/terraform-docs.yml

name: "Documentation: terraform-docs"

# yamllint disable-line rule:truthy
on:
  push:

jobs:
  docs:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      # https://github.com/actions/checkout
      - name: '☁️ Checkout Repository'
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      # see https://github.com/marketplace/actions/terraform-docs-gh-actions
      - name: Render documentation for repository and push changes back to branch
        uses: terraform-docs/gh-actions@main
        with:
          config-file: ".terraform-docs.yml"
          output-file: "README.md"
          output-method: inject
          git-push: true
          working-dir: "./"

...
